const access = {
    //stage and pfe
    "3":[  
        {
            METHOD:"GET",
            URL:"/demandeEntreprise/getAllDemandesEntreprise/:id_responsable/:etat/:year"
        },
        {
            METHOD:"POST",
            URL:"/confirmationDemande/sendMail"
        },
        {
            METHOD:"PATCH",
            URL:"/demandeEntreprise/updateVueDemande"
        },
        {
            METHOD:"PATCH",
            URL:"/demandeEntreprise/updateEtatEntretien"
        },
        //-----------------------
        {
            METHOD:"GET",
            URL:"/etudiantComp/getAll"
        },
        {
            METHOD:"GET",
            URL:"/etudiantComp/getCompetenceByEtudiant/:id_etudiant"
        },
        {
            METHOD:"GET",
            URL:"/etudiantComp/getDepartementsList"
        },
        {
            METHOD:"GET",
            URL:"/etudiantComp/getFilteredStudents/:id"
        },
        {
            METHOD:"POST",
            URL:"/confirmationDemande/contactStudent"
        },
        {
            METHOD:"GET",
            URL:"/etudiantComp/getContactedStudents/:id_responsable"
        },
        {
            METHOD:"GET",
            URL:"/etudiantComp/getFilteredStudentsContacte/:id/:id_resposable"
        },
        {
            METHOD:"POST",
            URL:"/etudiantComp/getAllEtudiantsByCompetences"
        },
        {
            METHOD:"POST",
            URL:"/etudiantComp/getAllEtudiantsContactesByCompetences"
        },
        //-----------------
        {
            METHOD:"POST",
            URL:"/competence/add"
        },
        {
            METHOD:"PATCH",
            URL:"/competence/update"
        },
        {
            METHOD:"DELETE",
            URL:"/competence/delete/:id_competence"
        },
        {
            METHOD:"GET",
            URL:"/competence/getAll/:id"
        },
        {
            METHOD:"GET",
            URL:"/competence/getCvByEtudiant/:id"
        },
        {
            METHOD:"GET",
            URL:"/competence/loadCompetences"
        },
        {
            METHOD:"GET",
            URL:"/competence/filterCompetences/:idomaine"
        },
        {
            METHOD:"POST",
            URL:"/etudiantComp/getAllEtudiantsByCompetences"
        },
        //---------------------
        {
            METHOD:"POST",
            URL:"/demandeEtudiantStageEntreprise/getAllDemandesEtudiant/add"
        },
        {
            METHOD:"PATCH",
            URL:"/demandeEtudiantStageEntreprise/getAllDemandesEtudiant/patch"
        },
        {
            METHOD:"DELETE",
            URL:"/demandeEtudiantStageEntreprise/getAllDemandesEtudiant/delete/:id_demande"
        },
        {
            METHOD:"GET",
            URL:"/demandeEtudiantStageEntreprise/getAllDemandesEtudiant/:id_etudiant/:etatDemande/:year"
        },
        //----------------
        {
            METHOD:"GET",
            URL:"/domaine/getAll"
        },
        //----------------
        {
            METHOD:"GET",
            URL:"/entreprise/getEntrepriseInfo/:id_responsable"
        },
        //---------------
        {
            METHOD:"GET",
            URL:"/experience/getAll/:id"
        },
        {
            METHOD:"POST",
            URL:"/experience/add"
        },
        {
            METHOD:"PATCH",
            URL:"/experience/update"
        },
        {
            METHOD:"DELETE",
            URL:"/experience/delete/:id_experience"
        },
        //------------------------
        {
            METHOD:"POST",
            URL:"/demandeEtudiantStageEntreprise/add"
        },
        {
            METHOD:"GET",
            URL:"/demandeEtudiantStageEntreprise/getAllPostulationsEtudiant/:id_etudiant"
        },
        //--------------------------
        {
            METHOD:"POST",
            URL:"/offrestage/add"
        },
        {
            METHOD:"PATCH",
            URL:"/offrestage/update"
        },
        {
            METHOD:"DELETE",
            URL:"/offrestage/delete/:id_offre_stage"
        },
        {
            METHOD:"GET",
            URL:"/offrestage/getAll/:id_responsable/:etat/:year"
        },
        {
            METHOD:"GET",
            URL:"/offrestage/getAllOffresEntreprise/:id_entreprise"
        },
        {
            METHOD:"GET",
            URL:"/offrestage/getOneOffreEntreprise/:id_offre_stage"
        },
        {
            METHOD:"GET",
            URL:"/offrestage/getAllOffresEntreprisNotRegistred/:id/:year"
        },
        {
            METHOD:"PATCH",
            URL:"/offrestage/update_Nbr_vue"
        },
        {
            METHOD:"PATCH",
            URL:"/offrestage/update_Nbr_postulations"
        },
        {
            METHOD:"PATCH",
            URL:"/offrestage/closeOpenOffre"
        },
        {
            METHOD:"GET",
            URL:"/offrestage/getAllOffresOuvertes/:id_responsable"
        },
        {
            METHOD:"GET",
            URL:"/offrestage/getOffresEtudiantsContactes/:id_responsable/:id_etudiant"
        },
        {
            METHOD:"PATCH",
            URL:"/offrestage/offreExpired"
        },
        {
            METHOD:"GET",
            URL:"/offrestage/loadAllOffres/:id_responsable"
        },
        //---------------------
        {
            METHOD:"GET",
            URL:"/stagiaires/getAllSatgiaresByOffre/${id_responsable}/${id_offre_stage}"
        },
    ]   
}