const acces={
    "public":[
        {METHOD:"POST",URL:"/public"},
        {METHOD:"GET",URL:"/master"},
        {METHOD:"POST",URL:"/users/login"},
        {METHOD:"POST",URL:"/evenementiel/club/getclubs"},
        {METHOD:"POST",URL:"/evenementiel/roles_and_teams/getroles"},
        {METHOD:"POST",URL:"/evenementiel/roles_and_teams/getTeams"},
        { URL:"/diplome/",METHOD:"GET"},
        { URL:"/etablissement/",METHOD:"GET"},
        { URL:"/admin/login",METHOD:"POST"},
        { URL:"/domaine/",METHOD:"GET"},
        { URL:"/classe/",METHOD:"GET"},
        { URL:"/departement/",METHOD:"GET"},
        { URL:"/gouvernerat/",METHOD:"GET"}, 
          { URL:"/niveau/",METHOD:"GET"},
          { URL:"/pays/",METHOD:"GET"},
          { URL:"/specialite/",METHOD:"GET"},
          { URL:"/user/login",METHOD:"POST"},
          { URL:"/ville/",METHOD:"GET"},
          { URL:"/situationEtudiant/",METHOD:"GET"},
          { URL:"/user/forgotPassword",METHOD:"PATCH"},
          { URL:"/user/resetPassword",METHOD:"PATCH"},
          { URL:"/user/activeVerification",METHOD:"PATCH"}

    ],
    "2":[
        {METHOD:"POST",URL:"/evenementiel/user/getOneUser"},
        {METHOD:"POST",URL:"/evenementiel/user/getClubUsers"},
        {METHOD:"POST",URL:"/evenementiel/user/getMembres"},
        {METHOD:"POST",URL:"/evenementiel/user/getResponsables"},
        {METHOD:"POST",URL:"/evenementiel/user/updateUserInfo"},
        {METHOD:"POST",URL:"/evenementiel/user/updateUserImage"},
        {METHOD:"POST",URL:"/evenementiel/roles_and_teams/getroles"},
        {METHOD:"POST",URL:"/evenementiel/roles_and_teams/getTeams"},
        {METHOD:"POST",URL:"/evenementiel/post/getposts"},
        {METHOD:"POST",URL:"/evenementiel/post/addpost"},
        {METHOD:"POST",URL:"/evenementiel/post/deletePost"},
        {METHOD:"POST",URL:"/evenementiel/post/addComment"},
        {METHOD:"POST",URL:"/evenementiel/post/getComments"},
        {METHOD:"POST",URL:"/evenementiel/post/deleteComment"},
        {METHOD:"POST",URL:"/evenementiel/sondage/getsondage"},
        {METHOD:"POST",URL:"/evenementiel/sondage/addsondage"},
        {METHOD:"POST",URL:"/evenementiel/sondage/deletesondage"},
        {METHOD:"POST",URL:"/evenementiel/sondage/addVote"},
        {METHOD:"POST",URL:"/evenementiel/sondage/getVotes"},
        {METHOD:"POST",URL:"/evenementiel/sondage/getVote"},
        {METHOD:"POST",URL:"/evenementiel/evenment/getevents"},
        {METHOD:"POST",URL:"/evenementiel/evenment/addevent"},
        {METHOD:"POST",URL:"/evenementiel/evenment/getClubEvents"},
        {METHOD:"POST",URL:"/evenementiel/evenment/deleteEvent"},
        {METHOD:"POST",URL:"/evenementiel/evenment/getOneEvent"},
        {METHOD:"POST",URL:"/evenementiel/evenment/updateEvent"},
        {METHOD:"POST",URL:"/evenementiel/participation/addParticipation"},
        {METHOD:"POST",URL:"/evenementiel/participation/getAllParticipation"},
        {METHOD:"POST",URL:"/evenementiel/participation/updatestatut"},
        {METHOD:"POST",URL:"/evenementiel/participation/deleteParticipation"},
        {METHOD:"POST",URL:"/evenementiel/participation/getOneUserParti"},
        {METHOD:"POST",URL:"/evenementiel/club/getclubs"},
        {METHOD:"POST",URL:"/evenementiel/club/getuserClubs"},
        {METHOD:"POST",URL:"/evenementiel/club/getClubYouAreAdminIn"},
        {METHOD:"POST",URL:"/evenementiel/club/isAdmin"},
        {METHOD:"POST",URL:"/evenementiel/calendrier/addcalendar"},
        {METHOD:"POST",URL:"/evenementiel/calendrier/getcalendar"},
        {METHOD:"POST",URL:"/evenementiel/calendrier/deletecalendar"},
        {METHOD:"POST",URL:"/evenementiel/demande/sendRequest"},
        {METHOD:"POST",URL:"/evenementiel/demande/getRequests"},
        {METHOD:"POST",URL:"/evenementiel/demande/acceptOrDeleteRequests"},
        {METHOD:"POST",URL:"/evenementiel/activites/getactivites"},
        {METHOD:"POST",URL:"/evenementiel/activites/addactivite"},
        {METHOD:"POST",URL:"/evenementiel/activites/deleteactivite"},
        { URL:"/bacclaureat/",METHOD:"POST"},
        { URL:"/bacclaureat/:id",METHOD:"GET"},
        { URL:"/bacclaureat/",METHOD:"PATCH"},
        { URL:"/cursus/",METHOD:"POST"},
        { URL:"/cursus/",METHOD:"GET"},
        { URL:"/cursus/:id",METHOD:"GET"},
        { URL:"/cursus/",METHOD:"PATCH"},
        { URL:"/cursus/:id",METHOD:"DELETE"},
        { URL:"/cursus/",METHOD:"POST"},
        { URL:"/cursus/:id",METHOD:"GET"},
        { URL:"/cursus/",METHOD:"PATCH"},
        { URL:"/etudiant/",METHOD:"POST"},
        { URL:"/etudiant/",METHOD:"GET"},
        { URL:"/etudiant/:id",METHOD:"GET"},
        { URL:"/etudiant/",METHOD:"PATCH"},
        { URL:"/user/:id",METHOD:"GET"},
        { URL:"/demandeMaster/",METHOD:"POST"},
        { URL:"/demandeMaster/:id",METHOD:"GET"},
        { URL:"/demandeMaster/confirm/:token",METHOD:"GET"},
        { URL:"/demandeMaster/confirmer",METHOD:"POST"},
        { URL:"/demandeMaster/:id",METHOD:"DELETE"}

    ],
    "3":[{METHOD:"GET",URL:"/master"}],
    "4":[
        {METHOD:"GET",URL:"/master"},
        { URL:"/admin/",METHOD:"PATCH"},
   { URL:"/admin/:id",METHOD:"GET"},
   { URL:"/classe/",METHOD:"POST"},
   { URL:"/classe/:id",METHOD:"GET"},
   { URL:"/classe/",METHOD:"PATCH"},
   { URL:"/classe/:id",METHOD:"DELETE"},
   { URL:"/departement/",METHOD:"POST"},
   { URL:"/departement/:id",METHOD:"GET"},
   { URL:"/departement/",METHOD:"PATCH"},
   { URL:"/departement/:id",METHOD:"DELETE"},
   { URL:"/domaine/",METHOD:"POST"},
   { URL:"/domaine/:id",METHOD:"GET"},
   { URL:"/domaine/",METHOD:"PATCH"},
   { URL:"/domaine/:id",METHOD:"DELETE"},  
   { URL:"/etablissement/",METHOD:"POST"},
   { URL:"/etablissement/:id",METHOD:"GET"},
   { URL:"/etablissement/",METHOD:"PATCH"},
   { URL:"/etablissement/:id",METHOD:"DELETE"},
   { URL:"/master/",METHOD:"POST"},
   { URL:"/master/",METHOD:"GET"},
   { URL:"/master/:id",METHOD:"GET"},
   { URL:"/master/",METHOD:"PATCH"},
   { URL:"/master/:id",METHOD:"DELETE"},
   { URL:"/master/applicants/:id",METHOD:"GET"},
   { URL:"/niveau/",METHOD:"POST"},
   { URL:"/niveau/:id",METHOD:"GET"},
   { URL:"/niveau/",METHOD:"PATCH"},
   { URL:"/niveau/:id",METHOD:"DELETE"},
   { URL:"/specialite/",METHOD:"POST"},
   { URL:"/specialite/:id",METHOD:"GET"},
   { URL:"/specialite/",METHOD:"PATCH"},
   { URL:"/specialite/:id",METHOD:"DELETE"},
   { URL:"/situationEtudiant/",METHOD:"POST"}, 
   { URL:"/situationEtudiant/:id",METHOD:"GET"},
   { URL:"/situationEtudiant/",METHOD:"PATCH"},
   { URL:"/situationEtudiant/:id",METHOD:"DELETE"},
   { URL:"/user/",METHOD:"POST"},
   { URL:"/user/",METHOD:"GET"},
   { URL:"/user/all",METHOD:"GET"},
   { URL:"/user/",METHOD:"PATCH"},
   {METHOD:"POST",URL:"file/add"}
   ,{METHOD:"PUT",URL:"file/updateAccept/:id"}
   ,{METHOD:"PUT",URL:"file/updateRefuse/:id"}
   ,{METHOD:"GET",URL:"file/getAll"}
   ,{METHOD:"GET",URL:"file/getAccpeter"}
   ,{METHOD:"GET",URL:"file/getEnAttente"}
   ,{METHOD:"GET",URL:"file/getRefuser"}
   ,{METHOD:"GET",URL:"file/getAllNumber"}
   ,{METHOD:"GET",URL:"file/getAllNumberA"}
   ,{METHOD:"GET",URL:"file/getAllNumberE"}
   ,{METHOD:"GET",URL:"file/getDocNbByMonth"}
   ,{METHOD:"GET",URL:"file/getAllNumberR"}
   ,{METHOD:"GET",URL:"file/getPapierIdFile/:id"}
   ,{METHOD:"PUT",URL:"Reclamation/updateReclamation/:id"}
   ,{METHOD:"PUT",URL:"Reclamation/updateReclamationRefuser/:id"}
   ,{METHOD:"GET",URL:"Reclamation/getAccpeter"}
   ,{METHOD:"GET",URL:"Reclamation/getEnAttente"}
   ,{METHOD:"GET",URL:"Reclamation/getRefuser"}
   ,{METHOD:"GET",URL:"Reclamation/getNumberReclamation"}
   ,{METHOD:"GET",URL:"Reclamation/getNumberReclamationA"}
   ,{METHOD:"GET",URL:"Reclamation/getNumberReclamationE"}
   ,{METHOD:"GET",URL:"Reclamation/getNumberReclamationR"}
   ,{METHOD:"GET",URL:"Reclamation/getDates"}
   ,{METHOD:"GET",URL:"Reclamation/getRecNbByMonth"}
    ],
    "5":[{METHOD:"GET",URL:"/master"}],
    "6":[{METHOD:"GET",URL:"/master"}],
    "7":[
        {METHOD:"GET",URL:"/master"},
        
],
    "8":[
        {METHOD:"GET",URL:"/master"},
        { URL:"/bacclaureat/",METHOD:"POST"},
        { URL:"/bacclaureat/:id",METHOD:"GET"},
        { URL:"/bacclaureat/",METHOD:"PATCH"},
        { URL:"/cursus/",METHOD:"POST"},
        { URL:"/cursus/",METHOD:"GET"},
        { URL:"/cursus/:id",METHOD:"GET"},
        { URL:"/cursus/",METHOD:"PATCH"},
        { URL:"/cursus/:id",METHOD:"DELETE"},
        { URL:"/cursus/",METHOD:"POST"},
        { URL:"/cursus/:id",METHOD:"GET"},
        { URL:"/cursus/",METHOD:"PATCH"},
        { URL:"/etudiant/",METHOD:"POST"},
        { URL:"/etudiant/",METHOD:"GET"},
        { URL:"/etudiant/:id",METHOD:"GET"},
        { URL:"/etudiant/",METHOD:"PATCH"},
        { URL:"/user/:id",METHOD:"GET"},
        { URL:"/demandeMaster/",METHOD:"POST"},
        { URL:"/demandeMaster/:id",METHOD:"GET"},
        { URL:"/demandeMaster/confirm/:token",METHOD:"GET"},
        { URL:"/demandeMaster/confirmer",METHOD:"POST"},
        { URL:"/demandeMaster/:id",METHOD:"DELETE"},
        {METHOD:"POST",URL:"file/add"},
	    {METHOD:"GET",URL:"file/getByIdUser/:id"},
		{METHOD:"GET",URL:"file/getAll"},
		{METHOD:"GET",URL:"file/getAccpeter"},
		{METHOD:"GET",URL:"file/getEnAttente"},
		{METHOD:"GET",URL:"file/getRefuser"},
		{METHOD:"GET",URL:"file/getAllPaperTypes"},
		{METHOD:"POST",URL:"Reclamation/addReclamation"},
		{METHOD:"PUT",URL:"Reclamation/deleteReclamation/:id"},
		{METHOD:"PUT",URL:"Reclamation/updateReclamationRefuser/:id"},
		{METHOD:"GET",URL:"Reclamation/get/:id"},
	    {METHOD:"GET",URL:"Reclamation/getById/:id"},
		{METHOD:"GET",URL:"Reclamation/relancerReclamtion/:id"},
		{METHOD:"GET",URL:"Reclamation/getAccpeter"},
		{METHOD:"GET",URL:"Reclamation/getEnAttente"},
		{METHOD:"GET",URL:"Reclamation/getAllClass"},
		{METHOD:"GET",URL:"Reclamation/getClassByIdEtudiant/:id"},
		{METHOD:"GET",URL:"Reclamation/getAllSpecialite"},
		{METHOD:"GET",URL:"Reclamation/getAllReclamTypes"}	
    ],
    "9":[
        {METHOD:"GET",URL:"/master"},
    { URL:"/bacclaureat/",METHOD:"POST"},
    { URL:"/bacclaureat/:id",METHOD:"GET"},
    { URL:"/bacclaureat/",METHOD:"PATCH"},
    { URL:"/cursus/",METHOD:"POST"},
    { URL:"/cursus/",METHOD:"GET"},
    { URL:"/cursus/:id",METHOD:"GET"},
    { URL:"/cursus/",METHOD:"PATCH"},
    { URL:"/cursus/:id",METHOD:"DELETE"},
    { URL:"/cursus/",METHOD:"POST"},
    { URL:"/cursus/:id",METHOD:"GET"},
    { URL:"/cursus/",METHOD:"PATCH"},
    { URL:"/etudiant/",METHOD:"POST"},
    { URL:"/etudiant/",METHOD:"GET"},
    { URL:"/etudiant/:id",METHOD:"GET"},
    { URL:"/etudiant/",METHOD:"PATCH"},
    { URL:"/user/:id",METHOD:"GET"},
    { URL:"/demandeMaster/",METHOD:"POST"},
    { URL:"/demandeMaster/:id",METHOD:"GET"},
    { URL:"/demandeMaster/confirm/:token",METHOD:"GET"},
    { URL:"/demandeMaster/confirmer",METHOD:"POST"},
    { URL:"/demandeMaster/:id",METHOD:"DELETE"},
    {METHOD:"POST",URL:"file/add"},
    {METHOD:"GET",URL:"file/getByIdUser/:id"},
    {METHOD:"GET",URL:"file/getAll"},
    {METHOD:"GET",URL:"file/getAccpeter"},
    {METHOD:"GET",URL:"file/getEnAttente"},
    {METHOD:"GET",URL:"file/getRefuser"},
    {METHOD:"GET",URL:"file/getAllPaperTypes"},
    {METHOD:"POST",URL:"Reclamation/addReclamation"},
    {METHOD:"PUT",URL:"Reclamation/deleteReclamation/:id"},
    {METHOD:"PUT",URL:"Reclamation/updateReclamationRefuser/:id"},
    {METHOD:"GET",URL:"Reclamation/get/:id"},
    {METHOD:"GET",URL:"Reclamation/getById/:id"},
    {METHOD:"GET",URL:"Reclamation/relancerReclamtion/:id"},
    {METHOD:"GET",URL:"Reclamation/getAccpeter"},
    {METHOD:"GET",URL:"Reclamation/getEnAttente"},
    {METHOD:"GET",URL:"Reclamation/getAllClass"},
    {METHOD:"GET",URL:"Reclamation/getClassByIdEtudiant/:id"},
    {METHOD:"GET",URL:"Reclamation/getAllSpecialite"},
    {METHOD:"GET",URL:"Reclamation/getAllReclamTypes"}],
    "10":[
        {METHOD:"GET",URL:"/master"},
        { URL:"/adminMaster/",METHOD:"POST"},
        { URL:"/adminMaster/",METHOD:"GET"},
        { URL:"/adminMaster/:id",METHOD:"GET"},
        { URL:"/adminMaster/",METHOD:"PATCH"},
        { URL:"/adminMaster/master/:id",METHOD:"GET"},
        { URL:"/adminMaster/exist/:email",METHOD:"GET"},
        { URL:"/adminMaster/master",METHOD:"POST"},
        { URL:"/adminMaster/exportdetaille",METHOD:"POST"},
        { URL:"/adminMaster/score",METHOD:"POST"},
        { URL:"/adminMaster/export",METHOD:"POST"},
        { URL:"/adminMaster/score/:id",METHOD:"GET"},
        { URL:"/adminMaster/score",METHOD:"PATCH"},
        { URL:"/demandeMaster/Adminmaster/:id",METHOD:"GET"},
        { URL:"/etatDemandeMaster/",METHOD:"POST"},
        { URL:"/etatDemandeMaster/",METHOD:"GET"},
        { URL:"/etatDemandeMaster/:id",METHOD:"GET"},
        { URL:"/etatDemandeMaster/",METHOD:"PATCH"},
        { URL:"/etatDemandeMaster/:id",METHOD:"DELETE"},
        { URL:"/master/",METHOD:"GET"},
        { URL:"/master/:id",METHOD:"GET"},
        { URL:"/demandeMaster/noteDemande",METHOD:"PATCH"},
        { URL:"/demandeMaster/:id",METHOD:"GET"},
        { URL:"/demandeMaster/",METHOD:"PATCH"},
        { URL:"/demandeMaster/",METHOD:"GET"},
        { URL:"/demandeMaster/etat",METHOD:"PATCH"},
        { URL:"/demandeMaster/:id",METHOD:"DELETE"}
    ],

}
module.exports = acces
