const acces={
    "public":[
        {METHOD:"POST",URL:"/public"},
        {METHOD:"GET",URL:"/master"},
        { METHOD:"GET",URL:"/demandeMaster/confirm/"},
        {METHOD:"POST",URL:"/users/login"},
        {METHOD:"POST",URL:"/users"},
        {METHOD:"POST",URL:"/evenementiel/club/getclubs"},
        {METHOD:"POST",URL:"/evenementiel/roles_and_teams/getroles"},
        {METHOD:"POST",URL:"/evenementiel/roles_and_teams/getTeams"},
        { URL:"/users/",METHOD:"GET"},
        { URL:"/admin/login",METHOD:"POST"},
        { URL:"/diplome/",METHOD:"GET"},
        { URL:"/etablissement",METHOD:"GET"},
        { URL:"/domaine",METHOD:"GET"},
        { URL:"/classe",METHOD:"GET"},
        { URL:"/departement",METHOD:"GET"},
        { URL:"/gouvernerat",METHOD:"GET"}, 
          { URL:"/niveau",METHOD:"GET"},
          { URL:"/pays",METHOD:"GET"},
          { URL:"/specialite",METHOD:"GET"},
          { URL:"/ville",METHOD:"GET"},
          { URL:"/users/login",METHOD:"POST"},
          { URL:"/situationEtudiant",METHOD:"GET"},
          { URL:"/users/forgotPassword",METHOD:"PATCH"},
          { URL:"/users/resetPassword",METHOD:"PATCH"},
          { URL:"/users/activeVerification",METHOD:"PATCH"}

    ],
    "2":[
        {METHOD:"POST",URL:"/evenementiel/user/getOneUser"},
        {METHOD:"POST",URL:"/evenementiel/user/getClubUsers"},
        {METHOD:"POST",URL:"/evenementiel/user/getMembres"},
        {METHOD:"POST",URL:"/evenementiel/user/getResponsables"},
        {METHOD:"POST",URL:"/evenementiel/user/updateUserInfo"},
        {METHOD:"POST",URL:"/evenementiel/user/updateUserImage"},
        {METHOD:"POST",URL:"/evenementiel/roles_and_teams/getroles"},
        {METHOD:"POST",URL:"/evenementiel/roles_and_teams/getTeams"},
        {METHOD:"POST",URL:"/evenementiel/post/getposts"},
        {METHOD:"POST",URL:"/evenementiel/post/addpost"},
        {METHOD:"POST",URL:"/evenementiel/post/deletePost"},
        {METHOD:"POST",URL:"/evenementiel/post/addComment"},
        {METHOD:"POST",URL:"/evenementiel/post/getComments"},
        {METHOD:"POST",URL:"/evenementiel/post/deleteComment"},
        {METHOD:"POST",URL:"/evenementiel/sondage/getsondage"},
        {METHOD:"POST",URL:"/evenementiel/sondage/addsondage"},
        {METHOD:"POST",URL:"/evenementiel/sondage/deletesondage"},
        {METHOD:"POST",URL:"/evenementiel/sondage/addVote"},
        {METHOD:"POST",URL:"/evenementiel/sondage/getVotes"},
        {METHOD:"POST",URL:"/evenementiel/sondage/getVote"},
        {METHOD:"POST",URL:"/evenementiel/evenment/getevents"},
        {METHOD:"POST",URL:"/evenementiel/evenment/addevent"},
        {METHOD:"POST",URL:"/evenementiel/evenment/getClubEvents"},
        {METHOD:"POST",URL:"/evenementiel/evenment/deleteEvent"},
        {METHOD:"POST",URL:"/evenementiel/evenment/getOneEvent"},
        {METHOD:"POST",URL:"/evenementiel/evenment/updateEvent"},
        {METHOD:"POST",URL:"/evenementiel/participation/addParticipation"},
        {METHOD:"POST",URL:"/evenementiel/participation/getAllParticipation"},
        {METHOD:"POST",URL:"/evenementiel/participation/updatestatut"},
        {METHOD:"POST",URL:"/evenementiel/participation/deleteParticipation"},
        {METHOD:"POST",URL:"/evenementiel/participation/getOneUserParti"},
        {METHOD:"POST",URL:"/evenementiel/club/getclubs"},
        {METHOD:"POST",URL:"/evenementiel/club/getuserClubs"},
        {METHOD:"POST",URL:"/evenementiel/club/getClubYouAreAdminIn"},
        {METHOD:"POST",URL:"/evenementiel/club/isAdmin"},
        {METHOD:"POST",URL:"/evenementiel/calendrier/addcalendar"},
        {METHOD:"POST",URL:"/evenementiel/calendrier/getcalendar"},
        {METHOD:"POST",URL:"/evenementiel/calendrier/deletecalendar"},
        {METHOD:"POST",URL:"/evenementiel/demande/sendRequest"},
        {METHOD:"POST",URL:"/evenementiel/demande/getRequests"},
        {METHOD:"POST",URL:"/evenementiel/demande/acceptOrDeleteRequests"},
        {METHOD:"POST",URL:"/evenementiel/activites/getactivites"},
        {METHOD:"POST",URL:"/evenementiel/activites/addactivite"},
        {METHOD:"POST",URL:"/evenementiel/activites/deleteactivite"},
        { URL:"/bacclaureat/",METHOD:"POST"},
        { URL:"/bacclaureat/",METHOD:"GET"},
        { URL:"/bacclaureat/",METHOD:"PATCH"},
        { URL:"/cursus",METHOD:"POST"},
        { URL:"/cursus",METHOD:"GET"},
        { URL:"/cursusG/",METHOD:"POST"},
        { URL:"/cursusG/",METHOD:"GET"},
        { URL:"/cursusG/",METHOD:"PATCH"},
        { URL:"/cursus/",METHOD:"GET"},
        { URL:"/cursus",METHOD:"PATCH"},
        { URL:"/cursus/",METHOD:"DELETE"},
        { URL:"/cursus",METHOD:"POST"},
        { URL:"/cursus/",METHOD:"GET"},
        { URL:"/cursus/",METHOD:"PATCH"},
        { URL:"/etudiant/",METHOD:"POST"},
        { URL:"/etudiant/",METHOD:"POST"},
        { URL:"/etudiant",METHOD:"GET"},
        { URL:"/etudiant/",METHOD:"GET"},
        { URL:"/etudiant/",METHOD:"PATCH"},
        { URL:"/etudiant",METHOD:"PATCH"},
        { URL:"/users/",METHOD:"GET"},
        { URL:"/demandeMaster",METHOD:"POST"},
        { URL:"/demandeMaster",METHOD:"GET"},
        { URL:"/demandeMaster/",METHOD:"GET"},
        { URL:"/demandeMaster/confirm/:token",METHOD:"GET"},
        { URL:"/demandeMaster/confirmer",METHOD:"POST"},
        { URL:"/demandeMaster/",METHOD:"DELETE"},
        //scolarite
        {METHOD:"POST",URL:"/addfile/add"},
        {METHOD:"DELETE",URL:"/DeleteFile/delete/"},
        {METHOD:"GET",URL:"/getAllFile/getAll"},
        {METHOD:"GET",URL:"/getFileAccepter/getAccpeter"},
        {METHOD:"GET",URL:"/getFileEnAttente/getEnAttente"},
        {METHOD:"GET",URL:"/getFileRefuser/getRefuser"},
        {METHOD:"GET",URL:"/addfile/getPapierIdFile/"},//GetDocById
        {METHOD:"GET",URL:"/getPaperTypes/getAllPaperTypes"},

        {METHOD:"POST",URL:"/addReclamation/addReclamation"},
        {METHOD:"DELETE",URL:"/DeleteReclamation/DeleteReclamation/"},
        {METHOD:"GET",URL:"/getAllReclamtion/getAllReclamtion"},
        {METHOD:"GET",URL:"/getReclamtionById/getById/"},//GetRecByID
        {METHOD:"GET",URL:"/getReclamtionEnAttente/getEnAttente"},
        {METHOD:"GET",URL:"/getAllReclamationById/getAllReclamationById/"},//getAllByIDUser
        {METHOD:"GET",URL:"/getAllReclamTypes/getAllReclamTypes"},
    //public
    { URL:"/diplome",METHOD:"GET"},
    { URL:"/situation",METHOD:"GET"},
    { URL:"/etablissement",METHOD:"GET"},
    { URL:"/domaine",METHOD:"GET"},
    { URL:"/classe",METHOD:"GET"},
    { URL:"/departement",METHOD:"GET"},
    { URL:"/gouvernerat",METHOD:"GET"}, 
      { URL:"/niveau",METHOD:"GET"},
      { URL:"/pays",METHOD:"GET"},
      { URL:"/specialite",METHOD:"GET"},
      { URL:"/ville",METHOD:"GET"},

    ],
    "3":[{METHOD:"GET",URL:"/master"}],
    "4":[
        {METHOD:"GET",URL:"/master"},
        { URL:"/admin/",METHOD:"PATCH"},
   { URL:"/admin/",METHOD:"GET"},
   { URL:"/classe/",METHOD:"POST"},
   { URL:"/classe/",METHOD:"GET"},
   { URL:"/classe/",METHOD:"PATCH"},
   { URL:"/classe/",METHOD:"DELETE"},
   { URL:"/departement/",METHOD:"POST"},
   { URL:"/departement/",METHOD:"GET"},
   { URL:"/departement/",METHOD:"PATCH"},
   { URL:"/departement/",METHOD:"DELETE"},
   { URL:"/domaine/",METHOD:"POST"},
   { URL:"/domaine/",METHOD:"GET"},
   { URL:"/domaine/",METHOD:"PATCH"},
   { URL:"/domaine/",METHOD:"DELETE"},  
   { URL:"/etablissement/",METHOD:"POST"},
   { URL:"/etablissement/",METHOD:"GET"},
   { URL:"/etablissement/",METHOD:"PATCH"},
   { URL:"/etablissement/",METHOD:"DELETE"},
   { URL:"/master/",METHOD:"POST"},
   { URL:"/master/",METHOD:"GET"},
   { URL:"/master/",METHOD:"GET"},
   { URL:"/master/",METHOD:"PATCH"},
   { URL:"/master/",METHOD:"DELETE"},
   { URL:"/master/applicants/",METHOD:"GET"},
   { URL:"/niveau/",METHOD:"POST"},
   { URL:"/niveau/",METHOD:"GET"},
   { URL:"/niveau/",METHOD:"PATCH"},
   { URL:"/niveau/",METHOD:"DELETE"},
   { URL:"/specialite/",METHOD:"POST"},
   { URL:"/specialite/",METHOD:"GET"},
   { URL:"/specialite/",METHOD:"PATCH"},
   { URL:"/specialite/",METHOD:"DELETE"},
   { URL:"/situationEtudiant/",METHOD:"POST"}, 
   { URL:"/situationEtudiant/",METHOD:"GET"},
   { URL:"/situationEtudiant/",METHOD:"PATCH"},
   { URL:"/situationEtudiant/",METHOD:"DELETE"},
   { URL:"/users/",METHOD:"POST"},
   { URL:"/users/",METHOD:"GET"},
   { URL:"/users/all",METHOD:"GET"},
   { URL:"/users/",METHOD:"PATCH"},
//scolarite
{METHOD:"GET",URL:"/getAllFile/getAll"},
{METHOD:"GET",URL:"/getFileAccepter/getAccpeter"},
{METHOD:"GET",URL:"/getFileEnAttente/getEnAttente"},
{METHOD:"GET",URL:"/getFileRefuser/getRefuser"},
{METHOD:"GET",URL:"/getAllNumber/getAllNumber"},
{METHOD:"GET",URL:"/getAllNumberA/getAllNumberA"},
{METHOD:"GET",URL:"/getAllNumberE/getAllNumberE"},
{METHOD:"GET",URL:"/getAllNumberR/getAllNumberR"},
{METHOD:"GET",URL:"getDocNbByMonth/getDocNbByMonth"},
{METHOD:"PUT",URL:"/updatefile/updateAccept/"},
{METHOD:"PUT",URL:"/updatefile/updateRefuse/"},

{METHOD:"GET",URL:"/getAllReclamtion/getAllReclamtion"},
{METHOD:"GET",URL:"/getReclamtionById/getById/"},//GetRecByID
{METHOD:"GET",URL:"/getReclamtionEnAttente/getEnAttente"},
{METHOD:"PUT",URL:"/updateReclamation/updateReclamation/"},
{METHOD:"PUT",URL:"/updateReclamation/updateReclamationRefuser/"},
{METHOD:"GET",URL:"/getRecNbByMonth/getRecNbByMonth"},
{METHOD:"GET",URL:"/getNumberReclamation/getNumberReclamation"},
{METHOD:"GET",URL:"/getNumberReclamationA/getNumberReclamationA"},
{METHOD:"GET",URL:"/getNumberReclamationE/getNumberReclamationE"},
{METHOD:"GET",URL:"/getNumberReclamationR/getNumberReclamationR"},
  //public
   { URL:"/diplome/",METHOD:"GET"},
   { URL:"/etablissement",METHOD:"GET"},
   { URL:"/domaine",METHOD:"GET"},
   { URL:"/classe",METHOD:"GET"},
   { URL:"/departement",METHOD:"GET"},
   { URL:"/gouvernerat",METHOD:"GET"}, 
     { URL:"/niveau",METHOD:"GET"},
     { URL:"/pays",METHOD:"GET"},
     { URL:"/specialite",METHOD:"GET"},
     { URL:"/ville",METHOD:"GET"},
    ],
    "5":[{METHOD:"GET",URL:"/master"}],
    "6":[{METHOD:"GET",URL:"/master"}],
    "7":[
        {METHOD:"GET",URL:"/master"},
        
],
    "8":[
        {METHOD:"GET",URL:"/master"},
        { URL:"/bacclaureat/",METHOD:"POST"},
        { URL:"/bacclaureat/",METHOD:"GET"},
        { URL:"/bacclaureat/",METHOD:"PATCH"},
        { URL:"/cursus",METHOD:"POST"},
        { URL:"/cursus",METHOD:"GET"},
        { URL:"/cursus/",METHOD:"GET"},
        { URL:"/cursus",METHOD:"PATCH"},
        { URL:"/cursus/",METHOD:"DELETE"},
        { URL:"/cursus",METHOD:"POST"},
        { URL:"/cursus/",METHOD:"GET"},
        { URL:"/cursusG/",METHOD:"POST"},
        { URL:"/cursusG/",METHOD:"GET"},
        { URL:"/cursusG/",METHOD:"PATCH"},
        { URL:"/cursus",METHOD:"PATCH"},
        { URL:"/etudiant",METHOD:"POST"},
        { URL:"/etudiant/",METHOD:"POST"},
        { URL:"/etudiant",METHOD:"GET"},
        { URL:"/etudiant/",METHOD:"GET"},
        { URL:"/etudiant",METHOD:"PATCH"},
        { URL:"/etudiant/",METHOD:"PATCH"},
        { URL:"/users/",METHOD:"GET"},
        { URL:"/demandeMaster",METHOD:"POST"},
        { URL:"/demandeMaster",METHOD:"GET"},
        { URL:"/demandeMaster/",METHOD:"GET"},
        { URL:"/demandeMaster/confirm/:token",METHOD:"GET"},
        { URL:"/demandeMaster/confirmer",METHOD:"POST"},
        { URL:"/demandeMaster/",METHOD:"DELETE"},
        //scolarite
        {METHOD:"POST",URL:"/addfile/add"},
        {METHOD:"DELETE",URL:"/DeleteFile/delete/"},
        {METHOD:"GET",URL:"/getAllFile/getAll"},
        {METHOD:"GET",URL:"/getFileAccepter/getAccpeter"},
        {METHOD:"GET",URL:"/getFileEnAttente/getEnAttente"},
        {METHOD:"GET",URL:"/getFileRefuser/getRefuser"},
        {METHOD:"GET",URL:"/addfile/getPapierIdFile/"},//GetDocById
        {METHOD:"GET",URL:"/getPaperTypes/getAllPaperTypes"},

        {METHOD:"POST",URL:"/addReclamation/addReclamation"},
        {METHOD:"DELETE",URL:"/DeleteReclamation/DeleteReclamation/"},
        {METHOD:"GET",URL:"/getAllReclamtion/getAllReclamtion"},
        {METHOD:"GET",URL:"/getReclamtionById/getById/"},//GetRecByID
        {METHOD:"GET",URL:"/getReclamtionEnAttente/getEnAttente"},
        {METHOD:"GET",URL:"/getAllReclamationById/getAllReclamationById/"},//getAllByIDUser
        {METHOD:"GET",URL:"/getAllReclamTypes/getAllReclamTypes"},
    //public
    { URL:"/diplome",METHOD:"GET"},
    { URL:"/situation",METHOD:"GET"},
    { URL:"/etablissement",METHOD:"GET"},
    { URL:"/domaine",METHOD:"GET"},
    { URL:"/classe",METHOD:"GET"},
    { URL:"/departement",METHOD:"GET"},
    { URL:"/gouvernerat",METHOD:"GET"}, 
      { URL:"/niveau",METHOD:"GET"},
      { URL:"/pays",METHOD:"GET"},
      { URL:"/specialite",METHOD:"GET"},
      { URL:"/ville",METHOD:"GET"},

    ],
    "9":[
        {METHOD:"GET",URL:"/master"},
    { URL:"/bacclaureat/",METHOD:"POST"},
    { URL:"/bacclaureat",METHOD:"POST"},
    { URL:"/bacclaureat/",METHOD:"GET"},
    { URL:"/bacclaureat/",METHOD:"PATCH"},
    { URL:"/bacclaureat",METHOD:"PATCH"},
    { URL:"/cursus/",METHOD:"POST"},
    { URL:"/cursus/",METHOD:"GET"},
    { URL:"/cursus/",METHOD:"GET"},
    { URL:"/cursus/",METHOD:"PATCH"},
    { URL:"/cursus/",METHOD:"DELETE"},
    { URL:"/cursus",METHOD:"POST"},
    { URL:"/cursusG/",METHOD:"POST"},
    { URL:"/cursusG",METHOD:"POST"},
    { URL:"/cursusG/",METHOD:"GET"},
    { URL:"/cursusG/",METHOD:"PATCH"},
    { URL:"/cursusG",METHOD:"PATCH"},
    { URL:"/cursus/",METHOD:"GET"},
    { URL:"/cursus",METHOD:"PATCH"},
    { URL:"/etudiant",METHOD:"POST"},
    { URL:"/etudiant/",METHOD:"POST"},
    { URL:"/etudiant",METHOD:"GET"},
    { URL:"/etudiant/",METHOD:"GET"},
    { URL:"/etudiant",METHOD:"PATCH"},
    { URL:"/etudiant/",METHOD:"PATCH"},
    { URL:"/users/",METHOD:"GET"},
    { URL:"/demandeMaster",METHOD:"POST"},
    { URL:"/demandeMaster",METHOD:"GET"},
    { URL:"/demandeMaster/",METHOD:"GET"},
    { URL:"/demandeMaster/confirm/:token",METHOD:"GET"},
    { URL:"/demandeMaster/confirmer",METHOD:"POST"},
    { URL:"/demandeMaster/",METHOD:"DELETE"},
    //scolarite
    {METHOD:"POST",URL:"/addfile/add"},
    {METHOD:"DELETE",URL:"/DeleteFile/delete/"},
    {METHOD:"GET",URL:"/getAllFile/getAll"},
    {METHOD:"GET",URL:"/getFileAccepter/getAccpeter"},
    {METHOD:"GET",URL:"/getFileEnAttente/getEnAttente"},
    {METHOD:"GET",URL:"/getFileRefuser/getRefuser"},
    {METHOD:"GET",URL:"/addfile/getPapierIdFile/"},//GetDocById
    {METHOD:"GET",URL:"/getPaperTypes/getAllPaperTypes"},
    {METHOD:"POST",URL:"/addReclamation/addReclamation"},
    {METHOD:"DELETE",URL:"/DeleteReclamation/DeleteReclamation/"},
    {METHOD:"GET",URL:"/getAllReclamtion/getAllReclamtion"},
    {METHOD:"GET",URL:"/getReclamtionById/getById/"},//GetRecByID
    {METHOD:"GET",URL:"/getReclamtionEnAttente/getEnAttente"},
    {METHOD:"GET",URL:"/getAllReclamationById/getAllReclamationById/"},//getAllByIDUser
    {METHOD:"GET",URL:"/getAllReclamTypes/getAllReclamTypes"},
    //public
    { URL:"/situation",METHOD:"GET"},
    { URL:"/diplome",METHOD:"GET"},
    { URL:"/etablissement",METHOD:"GET"},
    { URL:"/domaine",METHOD:"GET"},
    { URL:"/classe",METHOD:"GET"},
    { URL:"/departement",METHOD:"GET"},
    { URL:"/gouvernerat",METHOD:"GET"}, 
      { URL:"/niveau",METHOD:"GET"},
      { URL:"/pays",METHOD:"GET"},
      { URL:"/specialite",METHOD:"GET"},
      { URL:"/ville",METHOD:"GET"},

    ],
    "10":[
        {METHOD:"GET",URL:"/master"},
        { URL:"/adminMaster/",METHOD:"POST"},
        { URL:"/adminMaster/",METHOD:"GET"},
        { URL:"/adminMaster/",METHOD:"GET"},
        { URL:"/adminMaster/",METHOD:"PATCH"},
        { URL:"/adminMaster/master/",METHOD:"GET"},
        { URL:"/adminMaster/exist/:email",METHOD:"GET"},
        { URL:"/adminMaster/master",METHOD:"POST"},
        { URL:"/adminMaster/exportdetaille",METHOD:"POST"},
        { URL:"/adminMaster/score",METHOD:"POST"},
        { URL:"/adminMaster/score/",METHOD:"POST"},
        { URL:"/adminMaster/export",METHOD:"POST"},
        { URL:"/adminMaster/score/",METHOD:"GET"},
        { URL:"/adminMaster/score",METHOD:"GET"},
        { URL:"/adminMaster/score",METHOD:"PATCH"},
        { URL:"/adminMaster/score/",METHOD:"PATCH"},
        { URL:"/demandeMaster/Adminmaster/",METHOD:"GET"},
        { URL:"/etatDemandeMaster/",METHOD:"POST"},
        { URL:"/etatDemandeMaster/",METHOD:"GET"},
        { URL:"/etatDemandeMaster/",METHOD:"GET"},
        { URL:"/etatDemandeMaster/",METHOD:"PATCH"},
        { URL:"/etatDemandeMaster/",METHOD:"DELETE"},
        { URL:"/master/",METHOD:"GET"},
        { URL:"/master/",METHOD:"GET"},
        { URL:"/demandeMaster/noteDemande",METHOD:"PATCH"},
        { URL:"/demandeMaster/confirmer",METHOD:"POST"},
        { URL:"/demandeMaster/",METHOD:"GET"},
        { URL:"/demandeMaster/",METHOD:"PATCH"},
        { URL:"/demandeMaster/",METHOD:"GET"},
        { URL:"/demandeMaster/etat",METHOD:"PATCH"},
        { URL:"/demandeMaster/",METHOD:"DELETE"},
        { URL:"/diplome",METHOD:"GET"},
        { URL:"/etablissement",METHOD:"GET"},
        { URL:"/domaine",METHOD:"GET"},
        { URL:"/classe",METHOD:"GET"},
        { URL:"/departement",METHOD:"GET"},
        { URL:"/gouvernerat",METHOD:"GET"}, 
          { URL:"/niveau",METHOD:"GET"},
          { URL:"/pays",METHOD:"GET"},
          { URL:"/specialite",METHOD:"GET"},
          { URL:"/ville",METHOD:"GET"},
    ],

}
module.exports = acces
